default_language_version:
  python: python3.6

fail_fast: true

repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    args: [--quiet]
    name: 'Formatting python code using Black'
    language_version: python3.6
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 'v1.4.0'
  hooks:
  - id: python-no-log-warn
    name: 'Use logger.warning('
  - id: python-no-eval
    name: 'Check for eval()'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  # exclude: '.*\.md'
  - id: flake8
    name: 'Lint and check style with Flake8'
