default_language_version:
  python: python3.6

fail_fast: true

repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: mixed-line-ending
# - id: trailing-whitespace [--markdown-linebreak-ext=md]
  - id: trailing-whitespace
    exclude: '.*\.md'
  - id: flake8
